[project]
authors = ["Sejin Kim <hello@sejin.kim>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "pco"
platforms = ["win-64", "osx-arm64"]
version = "0.1.0"

[dependencies]
python = "3.11.*"
pytest = ">=8.3.5,<9"
selenium = ">=4.32.0,<5"
pandas = ">=2.2.3,<3"

[activation.env]
PCO_EMAIL = 
PCO_PASSWORD = 
PCO_APP_ID = 
PCO_API_KEY = 
CONNECT_GROUPS_CSV = 
COACH_GROUPS_CSV = 

[pypi-dependencies]
pypco = ">=1.2.0, <2"
pco = { path = ".", editable = true }

[tasks]
make-cgs = "python scripts/create_cg.py"
make-c = "python scripts/create_coach_group.py"
