[project]
authors = ["Sejin Kim <hello@sejin.kim>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "pco"
platforms = ["win-64", "osx-arm64"]
version = "0.1.0"

[dependencies]
python = "3.11.*"
pytest = ">=8.3.5,<9"
selenium = ">=4.32.0,<5"
pandas = ">=2.2.3,<3"

[activation.env]
PCO_EMAIL = "oladayo@me.com"
PCO_PASSWORD = "ABab12!@34199323"
PCO_APP_ID = "129f439b4c7aa0a2056aa8c9383f409a582319ed300e6a1b0fcb4d330cf2f6a8"
PCO_API_KEY = "pco_pat_1434b814f363d7d6e0df756fddd4149baad22de2ae1afe946cd210ecf3c2802b4e9d7bd7"
CONNECT_GROUPS_CSV = "src/Fall 2025 approved CG's - Sheet2.csv"
COACH_GROUPS_CSV = "src/Fall 2025 -Coach Group.csv"

[pypi-dependencies]
pypco = ">=1.2.0, <2"
pco = { path = ".", editable = true }

[tasks]
make-cgs = "python scripts/create_cg.py"
make-c = "python scripts/create_coach_group.py"
